allowBuilds:
  '@prisma/engines': true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
fetchRetries: 5
fetchRetryFactor: 2
fetchRetryMintimeout: 20000
fetchRetryMaxtimeout: 120000
fetchTimeout: 600000
networkConcurrency: 4
overrides:
  hono: 4.12.25

onlyBuiltDependencies:
  - "@prisma/engines"
  - msw
  - prisma
  - sharp
