import 'server-only'
import type { RiskLevel } from '@/lib/generated/prisma'

const GROQ_API_URL = 'https://api.groq.com/openai/v1/chat/completions'

export interface FiberMetricInput {
  networkSegment: string
  signalStrength: number
  signalLoss: number
  attenuation: number
  errorRate: number
  reflectionLevel?: number
  distance?: number
}

export interface FiberAiAnalysis {
  riskLevel: RiskLevel
  probability: number
  recommendation: string
  faultType: string
  explanation: string
}

export type FiberSenseHelpRole = 'admin' | 'engineer' | 'operations'

function fallbackAnalysis(input: FiberMetricInput): FiberAiAnalysis {
  const score =
    input.attenuation * 30 +
    input.errorRate * 12 +
    input.signalLoss * 8 +
    Math.max(0, Math.abs(input.signalStrength) - 20) * 4 +
    (input.reflectionLevel ?? 0) * 2

  const probability = Math.min(98, Math.max(12, Math.round(score)))
  const riskLevel: RiskLevel =
    probability >= 85
      ? 'CRITICAL'
      : probability >= 70
        ? 'HIGH'
        : probability >= 45
          ? 'MEDIUM'
          : 'LOW'

  return {
    riskLevel,
    probability,
    faultType:
      input.signalLoss > 3
        ? 'SIGNAL_LOSS'
        : input.attenuation > 0.45
          ? 'SIGNAL_ATTENUATION'
          : 'REFLECTION_FAULT',
    recommendation:
      riskLevel === 'CRITICAL'
        ? 'Dispatch a field team immediately and verify OTDR trace continuity.'
        : riskLevel === 'HIGH'
          ? 'Schedule inspection within 24 hours and monitor attenuation trend.'
          : 'Continue monitoring and compare against historical segment baseline.',
    explanation:
      'Computed locally because ai is not configured or returned an invalid response.',
  }
}

function parseGroqJson(content: string): FiberAiAnalysis | null {
  const json = content.match(/\{[\s\S]*\}/)?.[0]
  if (!json) return null

  try {
    const parsed = JSON.parse(json) as Partial<FiberAiAnalysis>
    if (
      !parsed.riskLevel ||
      !['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'].includes(parsed.riskLevel) ||
      typeof parsed.probability !== 'number' ||
      !parsed.recommendation
    ) {
      return null
    }

    return {
      riskLevel: parsed.riskLevel,
      probability: Math.min(100, Math.max(0, Math.round(parsed.probability))),
      recommendation: parsed.recommendation,
      faultType: parsed.faultType ?? 'SIGNAL_ATTENUATION',
      explanation: parsed.explanation ?? 'Generated by ai.',
    }
  } catch {
    return null
  }
}

export async function analyzeFiberMetrics(
  input: FiberMetricInput
): Promise<FiberAiAnalysis> {
  const apiKey = process.env.GROQ_API_KEY
  if (!apiKey) return fallbackAnalysis(input)

  const response = await fetch(GROQ_API_URL, {
    method: 'POST',
    headers: {
      authorization: `Bearer ${apiKey}`,
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      model: process.env.GROQ_MODEL ?? 'llama-3.3-70b-versatile',
      temperature: 0.1,
      response_format: { type: 'json_object' },
      messages: [
        {
          role: 'system',
          content:
            'You are FiberSense, an AI assistant for fiber optic network fault detection. Return only JSON with riskLevel, probability, recommendation, faultType, and explanation.',
        },
        {
          role: 'user',
          content: JSON.stringify(input),
        },
      ],
    }),
  })

  if (!response.ok) return fallbackAnalysis(input)

  const payload = (await response.json()) as {
    choices?: Array<{ message?: { content?: string } }>
  }
  const content = payload.choices?.[0]?.message?.content
  if (!content) return fallbackAnalysis(input)

  return parseGroqJson(content) ?? fallbackAnalysis(input)
}

function fallbackHelpAnswer(question: string, role: FiberSenseHelpRole) {
  const normalized = question.toLowerCase()

  if (normalized.includes('assign') || normalized.includes('task')) {
    return 'Open Maintenance or Assign Tasks, choose the detected fault, select a technical support user, set the priority, then submit. The technician can update the repair status from their task page.'
  }

  if (normalized.includes('location')) {
    return 'Open Detected Faults or Fault Locations, select the fault, then save the physical location. That location will appear in task assignment, assessments, and reports.'
  }

  if (normalized.includes('assessment') || normalized.includes('risk')) {
    return 'Open Assessments, select a detected fault, and generate an assessment. Live generated signals also create saved assessments automatically when the system detects risk.'
  }

  if (normalized.includes('report') || normalized.includes('csv') || normalized.includes('pdf')) {
    return 'Open Reports, select the time range, report type, and scope. Generate the report, then export it as CSV or use the PDF button to print only the report content.'
  }

  if (normalized.includes('user') || normalized.includes('role')) {
    return role === 'admin'
      ? 'Open Users to change account roles or status. Registration creates non-admin users; admins control elevated access from user management.'
      : 'Only administrators can change users and roles. Ask an administrator to update account access from User Management.'
  }

  return 'Use Live Monitoring to watch generated signals, Detected Faults to review issues and locations, Assessments to evaluate detected faults, and Reports to export system activity for a selected time range.'
}

export async function answerFiberSenseHelpQuestion(input: {
  question: string
  role: FiberSenseHelpRole
}) {
  const question = input.question.trim()
  if (!question) return 'Ask a question about faults, assessments, reports, users, or task assignment.'

  const apiKey = process.env.GROQ_API_KEY
  if (!apiKey) return fallbackHelpAnswer(question, input.role)

  const response = await fetch(GROQ_API_URL, {
    method: 'POST',
    headers: {
      authorization: `Bearer ${apiKey}`,
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      model: process.env.GROQ_MODEL ?? 'llama-3.3-70b-versatile',
      temperature: 0.2,
      max_tokens: 260,
      messages: [
        {
          role: 'system',
          content:
            'You are FiberSense Help, a concise assistant for a fiber optic fault detection dashboard. Answer only about this system. Keep answers under 90 words. Mention exact pages when useful: Live Monitoring, Detected Faults, Assessments, Assign Tasks, Reports, Users, Settings. Admin manages users/settings/reports. Network engineer monitors performance, faults, assessments, AI analysis, and issue response. Operations monitors alerts/status/critical faults and assigns repair tasks.',
        },
        {
          role: 'user',
          content: `Role: ${input.role}\nQuestion: ${question}`,
        },
      ],
    }),
  })

  if (!response.ok) return fallbackHelpAnswer(question, input.role)

  const payload = (await response.json()) as {
    choices?: Array<{ message?: { content?: string } }>
  }
  const answer = payload.choices?.[0]?.message?.content?.trim()
  return answer || fallbackHelpAnswer(question, input.role)
}
